apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-route
  namespace: centralized-auth
spec:
  http:
    - name: keycloak-http
      match:
        hosts:
          - "192.168.100.105"
        paths:
          - "/auth/*"
      backends:
        - serviceName: keycloak
          servicePort: 8080
