apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: centralized-auth
  labels:
    app: user-server
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: user-server
