apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
spec:
  type: ClusterIP
  ports:
    - name: apisix-gateway
      port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app.kubernetes.io/name: apisix
