apiVersion: v1
kind: Service
metadata:
  name: payment-server
  namespace: centralized-auth
  labels:
    app: payment-server
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: payment-server
